// FreightOps design tokens — same dark theme as FuelOps
export const T = {
  bg:        '#0a0f14',
  card:      '#111820',
  border:    '#1e2a38',
  amber:     '#f59e0b',
  amberGlow: 'rgba(245,158,11,0.08)',
  blue:      '#38bdf8',
  green:     '#4ade80',
  red:       '#f87171',
  teal:      '#2dd4bf',
  text:      '#e2e8f0',
  textDim:   '#64748b',
  textFaint: '#334155',
  font:      "'DM Mono', 'Fira Code', monospace",
};

export const s = {
  card: {
    background: T.card,
    border: `1px solid ${T.border}`,
    borderRadius: 6,
    padding: 20,
    marginBottom: 16,
  },
  label: {
    display: 'block',
    fontSize: 10,
    color: T.textDim,
    letterSpacing: 1.5,
    marginBottom: 6,
    fontFamily: T.font,
  },
  input: {
    background: '#0d141c',
    border: `1px solid ${T.border}`,
    borderRadius: 4,
    color: T.text,
    fontFamily: T.font,
    fontSize: 12,
    padding: '8px 10px',
    width: '100%',
    marginBottom: 12,
    outline: 'none',
    boxSizing: 'border-box',
  },
  th: {
    background: '#0d1420',
    color: T.textDim,
    fontSize: 9,
    fontFamily: T.font,
    letterSpacing: 1.5,
    padding: '8px 12px',
    textAlign: 'left',
    borderBottom: `1px solid ${T.border}`,
    whiteSpace: 'nowrap',
  },
  td: {
    padding: '10px 12px',
    fontSize: 12,
    borderBottom: `1px solid ${T.border}`,
    color: T.text,
    fontFamily: T.font,
  },
  tdNum: {
    padding: '10px 12px',
    fontSize: 12,
    borderBottom: `1px solid ${T.border}`,
    color: T.text,
    fontFamily: T.font,
    textAlign: 'right',
  },
  btn: (v) => ({
    background: v === 'ghost' ? 'transparent' : T.amber,
    border: `1px solid ${v === 'ghost' ? T.border : T.amber}`,
    borderRadius: 4,
    color: v === 'ghost' ? T.textDim : '#000',
    cursor: 'pointer',
    fontFamily: T.font,
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: 1.5,
    padding: '8px 16px',
    transition: 'all .15s',
  }),
};
